name: mvp_core
description: A generic Flutter implementation of the MVP (model/view/presenter) pattern which allows for more testable code.
version: 0.0.3
homepage: https://hatfeather.io
repository: https://github.com/HatFeather/mvp_core

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
